
version: 2.1


jobs:
  testrtax89x:
    docker:
      - image: paldier/swrt-docker:latest
        environment:
          PROJECT_DIR: "/home/docker/project"
          TERM: "xterm-256color"
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build rtax89x
          shell: /bin/sh
          command: |
            git clone --depth=1 https://github.com/SWRT-dev/rtax89x
            sudo ln -sf ~/qca-toolchains/openwrt-gcc463.arm /opt/
            cd rtax89x/release/src-qca-ipq806x
            make rt-ax89u

workflows:
  build-workflow:
    jobs:
      - testrtax89x

